package nutricion.vista;

import javax.swing.JOptionPane;
import nutricion.modelo.Comida;
import nutricion.persistencia.ComidaData;

/**
 *
 * @author ACER
 */
public class ComidaVista extends javax.swing.JInternalFrame {
    private ComidaData cdata = new ComidaData();
    private Comida c = null;

    /**
     * Creates new form ComidaVista
     */
    public ComidaVista() {
        initComponents();
        this.setSize(600,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jtf_tipo = new javax.swing.JTextField();
        jtf_calorias = new javax.swing.JTextField();
        jtf_detalle = new javax.swing.JTextField();
        jrb_baja = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jtf_cod = new javax.swing.JTextField();
        jb_nuevo = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setBackground(new java.awt.Color(255, 204, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Comidas");

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tipo:");

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Calorias (por 100gr):");

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Detalle:");

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Baja:");

        jtf_nombre.setBackground(new java.awt.Color(255, 102, 102));
        jtf_nombre.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jtf_nombre.setForeground(new java.awt.Color(0, 0, 0));
        jtf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombreActionPerformed(evt);
            }
        });

        jtf_tipo.setBackground(new java.awt.Color(255, 102, 102));
        jtf_tipo.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jtf_tipo.setForeground(new java.awt.Color(0, 0, 0));

        jtf_calorias.setBackground(new java.awt.Color(255, 102, 102));
        jtf_calorias.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jtf_calorias.setForeground(new java.awt.Color(0, 0, 0));

        jtf_detalle.setBackground(new java.awt.Color(255, 102, 102));
        jtf_detalle.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jtf_detalle.setForeground(new java.awt.Color(0, 0, 0));

        jrb_baja.setBackground(new java.awt.Color(255, 102, 102));

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Número:");

        jtf_cod.setBackground(new java.awt.Color(255, 102, 102));
        jtf_cod.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jtf_cod.setForeground(new java.awt.Color(255, 204, 255));

        jb_nuevo.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jb_nuevo.setForeground(new java.awt.Color(255, 102, 102));
        jb_nuevo.setText("Nuevo");
        jb_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_nuevoActionPerformed(evt);
            }
        });

        jb_guardar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jb_guardar.setForeground(new java.awt.Color(255, 102, 102));
        jb_guardar.setText("Guardar");
        jb_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarActionPerformed(evt);
            }
        });

        jb_eliminar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jb_eliminar.setForeground(new java.awt.Color(255, 102, 102));
        jb_eliminar.setText("Eliminar");
        jb_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jb_nuevo))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jb_guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                                .addComponent(jb_eliminar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jtf_nombre)
                                .addComponent(jtf_tipo)
                                .addComponent(jtf_calorias)
                                .addComponent(jtf_detalle, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                            .addComponent(jrb_baja)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_calorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtf_detalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jrb_baja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_eliminar)
                    .addComponent(jb_guardar)
                    .addComponent(jb_nuevo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jtf_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nombreActionPerformed

    private void jb_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminarActionPerformed
        try{
       Integer nro = Integer.parseInt(jtf_cod.getText());
       cdata.borrarComida(nro);
       } catch(NumberFormatException ex){
           JOptionPane.showMessageDialog(this, "Debe ingresar un número valido.");
      
       }
       limpiar();
    }//GEN-LAST:event_jb_eliminarActionPerformed

    private void jb_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_nuevoActionPerformed
        limpiar();
        c = null;
    }//GEN-LAST:event_jb_nuevoActionPerformed

    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed
        String nombre = jtf_nombre.getText();
        String tipo = jtf_tipo.getText();
        Integer calorias = Integer.parseInt(jtf_calorias.getText());
        String detalle = jtf_detalle.getText();
        Boolean baja = jrb_baja.isSelected();
        
        if(c==null){
            c = new Comida(nombre, tipo, calorias, detalle, baja);
            cdata.guardarComida(c);
        }
        
        limpiar();
    }//GEN-LAST:event_jb_guardarActionPerformed

    private void limpiar(){
        jtf_nombre.setText("");
        jtf_tipo.setText("");
        jtf_calorias.setText("");
        jtf_detalle.setText("");
        jrb_baja.setSelected(false);
        jtf_cod.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_nuevo;
    private javax.swing.JRadioButton jrb_baja;
    private javax.swing.JTextField jtf_calorias;
    private javax.swing.JTextField jtf_cod;
    private javax.swing.JTextField jtf_detalle;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_tipo;
    // End of variables declaration//GEN-END:variables
}
