package nutricion.vista;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import nutricion.modelo.Dieta;
import nutricion.persistencia.DietaData;

/**
 *
 * @author ACER
 */
public class DietaVista extends javax.swing.JInternalFrame {
    private DietaData ddata = new DietaData(); 
    private Dieta dieta = null;
    /**
     * Creates new form DietaVista
     */
    public DietaVista() {
        initComponents();
        this.setSize(600,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jd_inicio = new com.toedter.calendar.JDateChooser();
        jd_fin = new com.toedter.calendar.JDateChooser();
        jtf_pesofinal = new javax.swing.JTextField();
        jtf_calorias = new javax.swing.JTextField();
        jb_nuevo = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtf_nro = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Dieta");

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha de Inicio:");

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha de Fin:");

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Total calorias:");

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Peso final:");

        jtf_nombre.setBackground(new java.awt.Color(255, 102, 102));
        jtf_nombre.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jtf_nombre.setForeground(new java.awt.Color(0, 0, 0));
        jtf_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombreActionPerformed(evt);
            }
        });

        jd_inicio.setBackground(new java.awt.Color(255, 102, 102));
        jd_inicio.setForeground(new java.awt.Color(0, 0, 0));

        jd_fin.setBackground(new java.awt.Color(255, 102, 102));
        jd_fin.setForeground(new java.awt.Color(0, 0, 0));

        jtf_pesofinal.setBackground(new java.awt.Color(255, 102, 102));
        jtf_pesofinal.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jtf_pesofinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_calorias.setBackground(new java.awt.Color(255, 102, 102));
        jtf_calorias.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jtf_calorias.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jb_nuevo.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jb_nuevo.setForeground(new java.awt.Color(255, 102, 102));
        jb_nuevo.setText("Nuevo");
        jb_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_nuevoActionPerformed(evt);
            }
        });

        jb_guardar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jb_guardar.setForeground(new java.awt.Color(255, 102, 102));
        jb_guardar.setText("Guardar");
        jb_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Paciente:");

        jtf_nro.setBackground(new java.awt.Color(255, 102, 102));
        jtf_nro.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jtf_nro.setForeground(new java.awt.Color(0, 0, 0));
        jtf_nro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_nombre)
                            .addComponent(jd_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(jd_fin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_pesofinal)
                            .addComponent(jtf_calorias)
                            .addComponent(jtf_nro)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jb_nuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_guardar)))
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jd_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jd_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtf_pesofinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtf_calorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_nro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jb_guardar)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_nuevo)
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nombreActionPerformed

    private void jb_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_nuevoActionPerformed
        limpiar();
        dieta = null;
    }//GEN-LAST:event_jb_nuevoActionPerformed

    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed
        String nombre = jtf_nombre.getText();
        java.util.Date fechai = jd_inicio.getDate();
        LocalDate fechaInicio = fechai.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        java.util.Date fechaf = jd_fin.getDate();
        LocalDate fechaFinal = fechaf.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Float pesofinal = Float.parseFloat(jtf_pesofinal.getText());
        Integer calorias = Integer.parseInt(jtf_calorias.getText());
        Integer nro = Integer.parseInt(jtf_nro.getText());
        
        if(dieta == null){
            dieta = new Dieta(nombre, fechaInicio, fechaFinal, pesofinal, calorias);
            ddata.guardarDieta(dieta, nro);
        }
        
        limpiar();
    }//GEN-LAST:event_jb_guardarActionPerformed

    private void limpiar(){
        jtf_nombre.setText("");
        jd_inicio.setDate(new Date());
        jd_fin.setDate(new Date());
        jtf_pesofinal.setText("");
        jtf_calorias.setText("");
        jtf_nro.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_nuevo;
    private com.toedter.calendar.JDateChooser jd_fin;
    private com.toedter.calendar.JDateChooser jd_inicio;
    private javax.swing.JTextField jtf_calorias;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_nro;
    private javax.swing.JTextField jtf_pesofinal;
    // End of variables declaration//GEN-END:variables
}
