package nutricion.vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import nutricion.modelo.Paciente;
import nutricion.persistencia.PacienteData;

/**
 *
 * @author ACER
 */
public class ListadoPacientes extends javax.swing.JInternalFrame {

    private PacienteData pdata;
    private Paciente p;

    private ArrayList<Paciente> pacientesT;
    private ArrayList<Paciente> pacientesF;
    private ArrayList<Paciente> pacientesN;

    private DefaultTableModel modelo;

    /**
     * Creates new form Listado
     */
    public ListadoPacientes() {
        initComponents();
        this.setSize(600, 500);

        pdata = new PacienteData();
        pacientesT = (ArrayList<Paciente>) pdata.listarPacientes();
        pacientesF = (ArrayList<Paciente>) pdata.listarPacientesPesoLogrado();
        pacientesN = (ArrayList<Paciente>)pdata.listarPacientesNoLogrado();
        modelo = new DefaultTableModel();
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jrb_pacientes = new javax.swing.JRadioButton();
        jrb_pacientesF = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_pacientes = new javax.swing.JTable();
        jrb_pacienteno = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 204, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pacientes");

        jrb_pacientes.setBackground(new java.awt.Color(255, 204, 255));
        jrb_pacientes.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jrb_pacientes.setForeground(new java.awt.Color(255, 102, 102));
        jrb_pacientes.setText("Lista de todos los pacientes");
        jrb_pacientes.setBorder(null);
        jrb_pacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_pacientesActionPerformed(evt);
            }
        });

        jrb_pacientesF.setBackground(new java.awt.Color(255, 204, 255));
        jrb_pacientesF.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jrb_pacientesF.setForeground(new java.awt.Color(255, 102, 102));
        jrb_pacientesF.setText("Lista de pacientes que cumplieron objetivo");
        jrb_pacientesF.setBorder(null);
        jrb_pacientesF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_pacientesFActionPerformed(evt);
            }
        });

        jt_pacientes.setBackground(new java.awt.Color(255, 204, 255));
        jt_pacientes.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jt_pacientes.setForeground(new java.awt.Color(255, 102, 102));
        jt_pacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt_pacientes);

        jrb_pacienteno.setBackground(new java.awt.Color(255, 204, 255));
        jrb_pacienteno.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jrb_pacienteno.setForeground(new java.awt.Color(255, 102, 102));
        jrb_pacienteno.setText("Lista de pacientes que no lograron objetivo");
        jrb_pacienteno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_pacientenoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jrb_pacientes)
                        .addGap(18, 18, 18)
                        .addComponent(jrb_pacientesF))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jrb_pacienteno)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb_pacientes)
                    .addComponent(jrb_pacientesF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_pacienteno)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_pacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_pacientesActionPerformed
        borrarFilaTabla();
        jrb_pacientesF.setSelected(false);
        jrb_pacienteno.setSelected(false);
        cargarDatosPacientesT();
    }//GEN-LAST:event_jrb_pacientesActionPerformed

    private void jrb_pacientesFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_pacientesFActionPerformed
        borrarFilaTabla();
        jrb_pacientes.setSelected(false);
        jrb_pacienteno.setSelected(false);
        cargarDatosPacientesF();
    }//GEN-LAST:event_jrb_pacientesFActionPerformed

    private void jrb_pacientenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_pacientenoActionPerformed
        borrarFilaTabla();
        jrb_pacientes.setSelected(false);
        jrb_pacientesF.setSelected(false);
        cargarDatosPacientesN();
    }//GEN-LAST:event_jrb_pacientenoActionPerformed

    private void armarCabeceraTabla() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Nro");
        filaCabecera.add("Nombre");
        filaCabecera.add("Edad");
        filaCabecera.add("Altura");
        filaCabecera.add("Peso actual");
        filaCabecera.add("Peso buscado");

        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }
        jt_pacientes.setModel(modelo);
    }

    private void borrarFilaTabla() {
        int indice = modelo.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    private void cargarDatosPacientesT() {
        pacientesT = pdata.listarPacientes();
        for (Paciente p : pacientesT) {
            modelo.addRow(new Object[]{p.getNroPaciente(), p.getNombre(), p.getEdad(), p.getAltura(), p.getPesoActual(), p.getPesoBuscado()});
        }
    }

    private void cargarDatosPacientesF() {
        pacientesF = pdata.listarPacientesPesoLogrado();
        for (Paciente p : pacientesF) {
            modelo.addRow(new Object[]{p.getNroPaciente(), p.getNombre(), p.getEdad(), p.getAltura(), p.getPesoActual(), p.getPesoBuscado()});
        }
    }
    
    private void cargarDatosPacientesN(){
        pacientesN = pdata.listarPacientesNoLogrado();
        for (Paciente p : pacientesN) {
            modelo.addRow(new Object[]{p.getNroPaciente(), p.getNombre(), p.getEdad(), p.getAltura(), p.getPesoActual(), p.getPesoBuscado()});
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrb_pacienteno;
    private javax.swing.JRadioButton jrb_pacientes;
    private javax.swing.JRadioButton jrb_pacientesF;
    private javax.swing.JTable jt_pacientes;
    // End of variables declaration//GEN-END:variables
}
