package nutricion.vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import nutricion.modelo.Comida;
import nutricion.persistencia.ComidaData;

/**
 *
 * @author ACER
 */
public class ListadoComidas extends javax.swing.JInternalFrame {

    private ComidaData cdata;
    private Comida c;

    private ArrayList<Comida> comidasN;
    private ArrayList<Comida> comidasI;
    private ArrayList<Comida> comidasC;
    private ArrayList<Comida> comidasT;

    private DefaultTableModel modelo;

    /**
     * Creates new form ComidasVista
     */
    public ListadoComidas() {
        initComponents();
        this.setSize(600, 500);
        cdata = new ComidaData();
        modelo = new DefaultTableModel();
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jrb_nombre = new javax.swing.JRadioButton();
        jrb_ingrediente = new javax.swing.JRadioButton();
        jrb_calorias = new javax.swing.JRadioButton();
        jrb_tipo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_comidas = new javax.swing.JTable();
        jtf_nombre = new javax.swing.JTextField();
        jtf_ingrediente = new javax.swing.JTextField();
        jtf_calorias = new javax.swing.JTextField();
        jtf_tipo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Comidas");

        jrb_nombre.setBackground(new java.awt.Color(255, 204, 255));
        jrb_nombre.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jrb_nombre.setForeground(new java.awt.Color(255, 102, 102));
        jrb_nombre.setText("Por nombre");
        jrb_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_nombreActionPerformed(evt);
            }
        });

        jrb_ingrediente.setBackground(new java.awt.Color(255, 204, 255));
        jrb_ingrediente.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jrb_ingrediente.setForeground(new java.awt.Color(255, 102, 102));
        jrb_ingrediente.setText("Por ingrediente");
        jrb_ingrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_ingredienteActionPerformed(evt);
            }
        });

        jrb_calorias.setBackground(new java.awt.Color(255, 204, 255));
        jrb_calorias.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jrb_calorias.setForeground(new java.awt.Color(255, 102, 102));
        jrb_calorias.setText("Por calorias");
        jrb_calorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_caloriasActionPerformed(evt);
            }
        });

        jrb_tipo.setBackground(new java.awt.Color(255, 204, 255));
        jrb_tipo.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jrb_tipo.setForeground(new java.awt.Color(255, 102, 102));
        jrb_tipo.setText("Por tipo");
        jrb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_tipoActionPerformed(evt);
            }
        });

        jt_comidas.setBackground(new java.awt.Color(255, 204, 255));
        jt_comidas.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jt_comidas.setForeground(new java.awt.Color(255, 102, 102));
        jt_comidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt_comidas);

        jtf_nombre.setBackground(new java.awt.Color(255, 102, 102));
        jtf_nombre.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jtf_nombre.setForeground(new java.awt.Color(255, 204, 255));
        jtf_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_ingrediente.setBackground(new java.awt.Color(255, 102, 102));
        jtf_ingrediente.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jtf_ingrediente.setForeground(new java.awt.Color(255, 204, 255));
        jtf_ingrediente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_calorias.setBackground(new java.awt.Color(255, 102, 102));
        jtf_calorias.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jtf_calorias.setForeground(new java.awt.Color(255, 204, 255));
        jtf_calorias.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_tipo.setBackground(new java.awt.Color(255, 102, 102));
        jtf_tipo.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jtf_tipo.setForeground(new java.awt.Color(255, 204, 255));
        jtf_tipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrb_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_ingrediente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_ingrediente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jtf_calorias))
                    .addComponent(jrb_calorias))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jtf_tipo))
                    .addComponent(jrb_tipo))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb_nombre)
                    .addComponent(jrb_ingrediente)
                    .addComponent(jrb_calorias)
                    .addComponent(jrb_tipo))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_ingrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_calorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_nombreActionPerformed
        borrarFilaTabla();
        jrb_ingrediente.setSelected(false);
        jrb_calorias.setSelected(false);
        jrb_tipo.setSelected(false);
        String nombre = jtf_nombre.getText();
        cargarDatosComidasN(nombre);
        limpiar();
    }//GEN-LAST:event_jrb_nombreActionPerformed

    private void jrb_ingredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_ingredienteActionPerformed
        borrarFilaTabla();
        jrb_nombre.setSelected(false);
        jrb_calorias.setSelected(false);
        jrb_tipo.setSelected(false);
        String ingrediente = jtf_ingrediente.getText();
        cargarDatosComidasI(ingrediente);
        limpiar();
    }//GEN-LAST:event_jrb_ingredienteActionPerformed

    private void jrb_caloriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_caloriasActionPerformed
        borrarFilaTabla();
        jrb_nombre.setSelected(false);jrb_nombre.setSelected(false);
        jrb_ingrediente.setSelected(false);
        jrb_tipo.setSelected(false);
        Integer calorias = Integer.parseInt(jtf_calorias.getText());
        cargarDatosComidasC(calorias);
        limpiar();
    }//GEN-LAST:event_jrb_caloriasActionPerformed

    private void jrb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_tipoActionPerformed
        borrarFilaTabla();
        jrb_nombre.setSelected(false);
        jrb_ingrediente.setSelected(false);
        jrb_calorias.setSelected(false);
        String tipo = jtf_tipo.getText();
        cargarDatosComidasT(tipo);
        limpiar();
    }//GEN-LAST:event_jrb_tipoActionPerformed

    private void armarCabeceraTabla() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Codigo");
        filaCabecera.add("Nombre");
        filaCabecera.add("Tipo");
        filaCabecera.add("Calorias (por 100 gr)");
        filaCabecera.add("Detalle");
        filaCabecera.add("Baja");

        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }
        jt_comidas.setModel(modelo);
    }

    private void borrarFilaTabla() {
        int indice = modelo.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    private void cargarDatosComidasN(String n) {
        comidasN = cdata.listarComidasPorNombre(n);
        for (Comida c : comidasN) {
            modelo.addRow(new Object[]{c.getCodComida(), c.getNombre(), c.getTipoComida(), c.getCaloriasPor100g(), c.getDetalle(), c.isBaja()});
        }
    }

    private void cargarDatosComidasI(String i) {
        comidasI = cdata.listarComidasPorIngrediente(i);
        for (Comida c : comidasI) {
            modelo.addRow(new Object[]{c.getCodComida(), c.getNombre(), c.getTipoComida(), c.getCaloriasPor100g(), c.getDetalle(), c.isBaja()});
        }
    }

    private void cargarDatosComidasC(int caloria) {
        comidasC = cdata.listarComidasPorCalorias(caloria);
        for (Comida c : comidasC) {
            modelo.addRow(new Object[]{c.getCodComida(), c.getNombre(), c.getTipoComida(), c.getCaloriasPor100g(), c.getDetalle(), c.isBaja()});
        }
    }

    private void cargarDatosComidasT(String t) {
        comidasT = cdata.listarComidasPorTipo(t);
        for (Comida c : comidasT) {
            modelo.addRow(new Object[]{c.getCodComida(), c.getNombre(), c.getTipoComida(), c.getCaloriasPor100g(), c.getDetalle(), c.isBaja()});
        }
    }
    
    private void limpiar(){
        jtf_nombre.setText("");
        jtf_ingrediente.setText("");
        jtf_calorias.setText("");
        jtf_tipo.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrb_calorias;
    private javax.swing.JRadioButton jrb_ingrediente;
    private javax.swing.JRadioButton jrb_nombre;
    private javax.swing.JRadioButton jrb_tipo;
    private javax.swing.JTable jt_comidas;
    private javax.swing.JTextField jtf_calorias;
    private javax.swing.JTextField jtf_ingrediente;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_tipo;
    // End of variables declaration//GEN-END:variables
}
