package nutricion.vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import nutricion.modelo.MenuDiario;
import nutricion.modelo.RenglonComida;
import nutricion.persistencia.MenuDiarioData;
import nutricion.persistencia.RenglonComidaData;

/**
 *
 * @author ACER
 */
public class MenuVista extends javax.swing.JInternalFrame {

    private MenuDiarioData mddata;
    private RenglonComidaData rcdata;
    private MenuDiario md;

    private DefaultTableModel modelo;

    /**
     * Creates new form MenuVista
     */
    public MenuVista() {
        initComponents();
        this.setSize(600, 500);
        mddata = new MenuDiarioData();
        rcdata = new RenglonComidaData();
        modelo = new DefaultTableModel();
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_ingredientes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtf_cod = new javax.swing.JTextField();
        jb_crearmenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_menu = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 204, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu sugerido");

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingredientes que quiere en su dieta:");

        jtf_ingredientes.setBackground(new java.awt.Color(255, 102, 102));
        jtf_ingredientes.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jtf_ingredientes.setForeground(new java.awt.Color(0, 0, 0));
        jtf_ingredientes.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese el código de dieta:");

        jtf_cod.setBackground(new java.awt.Color(255, 102, 102));
        jtf_cod.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jtf_cod.setForeground(new java.awt.Color(0, 0, 0));
        jtf_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_codActionPerformed(evt);
            }
        });

        jb_crearmenu.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jb_crearmenu.setForeground(new java.awt.Color(255, 102, 102));
        jb_crearmenu.setText("Generar menú");
        jb_crearmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearmenuActionPerformed(evt);
            }
        });

        jt_menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_ingredientes)
                            .addComponent(jtf_cod, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jb_crearmenu)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 66, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_ingredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_crearmenu)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_codActionPerformed

    private void jb_crearmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearmenuActionPerformed
        borrarFilaTabla();
        String i = jtf_ingredientes.getText();
        String[] separado = i.split(",");

        ArrayList<String> ingredientes = new ArrayList<>();

        for (String parte : separado) {
            if (!parte.trim().isEmpty()) {
                ingredientes.add(parte.trim().toLowerCase());
            }
        }
        Integer d = Integer.parseInt(jtf_cod.getText());
        mddata.generarMenuSugerido(ingredientes, d);

        ArrayList<MenuDiario> menus = mddata.obtenerMenusPorDieta(d); // obtenés todos los menús de esa dieta

        for (MenuDiario menu : menus) {
            Integer diaNro = menu.getDiaNro();
            String nombreDia = obtenerNombreDelDia(diaNro); // si ya lo tenés, perfecto

            ArrayList<RenglonComida> renglones = rcdata.listarRenglonesPorMenu(menu.getCodMenu());

            for (RenglonComida r : renglones) {
                String alimento = r.getAlimento().getNombre();
                double cantidad = r.getCantidadGrs();
                int calorias = r.getSubtotalCalorias();

                modelo.addRow(new Object[]{"Día " + diaNro + " - " + nombreDia, alimento, cantidad, calorias});
            }
        }

        limpiar();
    }

    private void armarCabeceraTabla() {
        modelo.addColumn("Dia");
        modelo.addColumn("Alimento");
        modelo.addColumn("Cantidad (gr)");
        modelo.addColumn("Subtotal calorias");
        jt_menu.setModel(modelo);
    }

    private void borrarFilaTabla() {
        int indice = modelo.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    private void limpiar() {
        jtf_ingredientes.setText("");
        jtf_cod.setText("");
    }

    private String obtenerNombreDelDia(int diaNro) {
        switch (diaNro) {
            case 1:
                return "Lunes";
            case 2:
                return "Martes";
            case 3:
                return "Miércoles";
            case 4:
                return "Jueves";
            case 5:
                return "Viernes";
            case 6:
                return "Sábado";
            case 7:
                return "Domingo";
            default:
                return "Día " + diaNro;
        }
    }//GEN-LAST:event_jb_crearmenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_crearmenu;
    private javax.swing.JTable jt_menu;
    private javax.swing.JTextField jtf_cod;
    private javax.swing.JTextField jtf_ingredientes;
    // End of variables declaration//GEN-END:variables
}
