package nutricion.vista;

import javax.swing.JOptionPane;
import nutricion.modelo.Paciente;
import nutricion.persistencia.PacienteData;

/**
 *
 * @author ACER
 */
public class PacienteVista extends javax.swing.JInternalFrame {
    private PacienteData pdata = new PacienteData();
    private Paciente paciente = null;

    /**
     * Creates new form PacienteVista
     */
    public PacienteVista() {
        initComponents();
        this.setSize(600,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jtf_edad = new javax.swing.JTextField();
        jtf_altura = new javax.swing.JTextField();
        jtf_pesoactual = new javax.swing.JTextField();
        jtf_pesobuscado = new javax.swing.JTextField();
        jb_nuevo = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_borrar = new javax.swing.JButton();
        jb_modificar = new javax.swing.JButton();
        jtf_numero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setBackground(new java.awt.Color(255, 204, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setBackground(new java.awt.Color(255, 204, 255));
        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Paciente");

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Edad: ");

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Altura:");

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Peso actual:");

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Peso buscado:");

        jtf_nombre.setBackground(new java.awt.Color(255, 102, 102));
        jtf_nombre.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jtf_nombre.setForeground(new java.awt.Color(0, 0, 0));
        jtf_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_edad.setBackground(new java.awt.Color(255, 102, 102));
        jtf_edad.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jtf_edad.setForeground(new java.awt.Color(0, 0, 0));
        jtf_edad.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_altura.setBackground(new java.awt.Color(255, 102, 102));
        jtf_altura.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jtf_altura.setForeground(new java.awt.Color(0, 0, 0));
        jtf_altura.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_pesoactual.setBackground(new java.awt.Color(255, 102, 102));
        jtf_pesoactual.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtf_pesoactual.setForeground(new java.awt.Color(0, 0, 0));
        jtf_pesoactual.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jtf_pesobuscado.setBackground(new java.awt.Color(255, 102, 102));
        jtf_pesobuscado.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jtf_pesobuscado.setForeground(new java.awt.Color(0, 0, 0));
        jtf_pesobuscado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jb_nuevo.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jb_nuevo.setForeground(new java.awt.Color(255, 102, 102));
        jb_nuevo.setText("Nuevo");
        jb_nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_nuevoActionPerformed(evt);
            }
        });

        jb_guardar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jb_guardar.setForeground(new java.awt.Color(255, 102, 102));
        jb_guardar.setText("Guardar");
        jb_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarActionPerformed(evt);
            }
        });

        jb_borrar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jb_borrar.setForeground(new java.awt.Color(255, 102, 102));
        jb_borrar.setText("Borrar");
        jb_borrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_borrarActionPerformed(evt);
            }
        });

        jb_modificar.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jb_modificar.setForeground(new java.awt.Color(255, 102, 102));
        jb_modificar.setText("Modificar");
        jb_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarActionPerformed(evt);
            }
        });

        jtf_numero.setBackground(new java.awt.Color(255, 102, 102));
        jtf_numero.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jtf_numero.setForeground(new java.awt.Color(0, 0, 0));
        jtf_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_numeroActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Número:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(jb_guardar)
                                .addGap(65, 65, 65)
                                .addComponent(jb_modificar)
                                .addGap(88, 88, 88)
                                .addComponent(jb_borrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtf_nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                    .addComponent(jtf_edad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_altura, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_pesoactual, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_pesobuscado, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel1)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtf_pesoactual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_nuevo)
                            .addComponent(jb_guardar)
                            .addComponent(jb_modificar)
                            .addComponent(jb_borrar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jtf_pesobuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_nuevoActionPerformed
        limpiar();
        paciente = null;
    }//GEN-LAST:event_jb_nuevoActionPerformed

    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed
        String nombre = jtf_nombre.getText();
        Integer edad = Integer.parseInt(jtf_edad.getText());
        Float altura = Float.parseFloat(jtf_altura.getText());
        Float pesoA = Float.parseFloat(jtf_pesoactual.getText());
        Float pesoB= Float.parseFloat(jtf_pesobuscado.getText());
        
        if(paciente==null){
            paciente = new Paciente(nombre, edad, altura, pesoA, pesoB);
            pdata.guardarPaciente(paciente);
        }
        
        limpiar();
    }//GEN-LAST:event_jb_guardarActionPerformed

    private void jb_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarActionPerformed
        String nombre = jtf_nombre.getText();
        Integer edad = Integer.parseInt(jtf_edad.getText());
        Float altura = Float.parseFloat(jtf_altura.getText());
        Float pesoA = Float.parseFloat(jtf_pesoactual.getText());
        Float pesoB= Float.parseFloat(jtf_pesobuscado.getText());
        
        pdata.actualizarPesoActual(pesoA, nombre);
        limpiar();
        
    }//GEN-LAST:event_jb_modificarActionPerformed

    private void jb_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_borrarActionPerformed
       try{
       Integer nro = Integer.parseInt(jtf_numero.getText());
       pdata.borrarPaciente(nro);
       } catch(NumberFormatException ex){
           JOptionPane.showMessageDialog(this, "Debe ingresar un número valido.");
      
       }
       limpiar();
    }//GEN-LAST:event_jb_borrarActionPerformed

    private void jtf_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_numeroActionPerformed
    
    private void limpiar(){
        jtf_nombre.setText("");
        jtf_edad.setText("");
        jtf_altura.setText("");
        jtf_pesoactual.setText("");
        jtf_pesobuscado.setText("");
        jtf_numero.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JButton jb_borrar;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_modificar;
    private javax.swing.JButton jb_nuevo;
    private javax.swing.JTextField jtf_altura;
    private javax.swing.JTextField jtf_edad;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_numero;
    private javax.swing.JTextField jtf_pesoactual;
    private javax.swing.JTextField jtf_pesobuscado;
    // End of variables declaration//GEN-END:variables
}
