package nutricion.vista;

import java.awt.Graphics;
import java.awt.Image;
import java.util.TreeSet;
import javax.swing.ImageIcon;
import nutricion.modelo.Paciente;

/**
 *
 * @author ACER
 */
public class PrincipalVista extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalVista
     */
    public PrincipalVista() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(800, 620);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jFileChooser1 = new javax.swing.JFileChooser();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        ImageIcon icono= new ImageIcon(getClass().getResource("/nutricion/recursos/fondonutricionista.png"));
        Image imagen= icono.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent (Graphics g){
                g.drawImage(imagen, 0, 0, getWidth(), getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_paciente = new javax.swing.JMenu();
        jmi_infopaciente = new javax.swing.JMenuItem();
        jm_dieta = new javax.swing.JMenu();
        jmi_infodieta = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jm_consulta = new javax.swing.JMenu();
        jmi_verdieta = new javax.swing.JMenuItem();
        jmi_menusugerido = new javax.swing.JMenuItem();
        jmi_comidas = new javax.swing.JMenuItem();
        jmi_lista = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem4.setText("jMenuItem4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 102, 102));

        jm_paciente.setBackground(new java.awt.Color(255, 204, 255));
        jm_paciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204)));
        jm_paciente.setForeground(new java.awt.Color(0, 51, 255));
        jm_paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nutricion/recursos/paciente.png"))); // NOI18N
        jm_paciente.setToolTipText("");
        jm_paciente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jm_paciente.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jm_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_pacienteActionPerformed(evt);
            }
        });

        jmi_infopaciente.setBackground(new java.awt.Color(255, 204, 255));
        jmi_infopaciente.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jmi_infopaciente.setForeground(new java.awt.Color(51, 51, 255));
        jmi_infopaciente.setText("Información paciente");
        jmi_infopaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_infopacienteActionPerformed(evt);
            }
        });
        jm_paciente.add(jmi_infopaciente);

        jMenuBar1.add(jm_paciente);

        jm_dieta.setBackground(new java.awt.Color(255, 204, 255));
        jm_dieta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nutricion/recursos/dieta.png"))); // NOI18N

        jmi_infodieta.setBackground(new java.awt.Color(255, 204, 255));
        jmi_infodieta.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jmi_infodieta.setForeground(new java.awt.Color(51, 51, 255));
        jmi_infodieta.setText("Información dieta");
        jmi_infodieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_infodietaActionPerformed(evt);
            }
        });
        jm_dieta.add(jmi_infodieta);

        jMenuItem2.setBackground(new java.awt.Color(255, 204, 255));
        jMenuItem2.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(51, 51, 255));
        jMenuItem2.setText("Información comida");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jm_dieta.add(jMenuItem2);

        jMenuBar1.add(jm_dieta);

        jm_consulta.setBackground(new java.awt.Color(255, 204, 255));
        jm_consulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204)));
        jm_consulta.setForeground(new java.awt.Color(0, 51, 255));
        jm_consulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nutricion/recursos/consulta.png"))); // NOI18N
        jm_consulta.setFocusable(false);
        jm_consulta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jmi_verdieta.setBackground(new java.awt.Color(255, 204, 255));
        jmi_verdieta.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jmi_verdieta.setForeground(new java.awt.Color(51, 51, 255));
        jmi_verdieta.setText("Ver dieta");
        jmi_verdieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_verdietaActionPerformed(evt);
            }
        });
        jm_consulta.add(jmi_verdieta);

        jmi_menusugerido.setBackground(new java.awt.Color(255, 204, 255));
        jmi_menusugerido.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jmi_menusugerido.setForeground(new java.awt.Color(51, 51, 255));
        jmi_menusugerido.setText("Menu sugerido");
        jmi_menusugerido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_menusugeridoActionPerformed(evt);
            }
        });
        jm_consulta.add(jmi_menusugerido);

        jmi_comidas.setBackground(new java.awt.Color(255, 204, 255));
        jmi_comidas.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jmi_comidas.setForeground(new java.awt.Color(51, 51, 255));
        jmi_comidas.setText("Lista comidas");
        jmi_comidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_comidasActionPerformed(evt);
            }
        });
        jm_consulta.add(jmi_comidas);

        jmi_lista.setBackground(new java.awt.Color(255, 204, 255));
        jmi_lista.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jmi_lista.setForeground(new java.awt.Color(51, 51, 255));
        jmi_lista.setText("Lista pacientes");
        jmi_lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_listaActionPerformed(evt);
            }
        });
        jm_consulta.add(jmi_lista);

        jMenuBar1.add(jm_consulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_comidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_comidasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ListadoComidas comidas = new ListadoComidas();
        comidas.setVisible(true);
        escritorio.add(comidas);
    }//GEN-LAST:event_jmi_comidasActionPerformed

    private void jmi_infopacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_infopacienteActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        PacienteVista paciente = new PacienteVista();
        paciente.setVisible(true);
        escritorio.add(paciente);
    }//GEN-LAST:event_jmi_infopacienteActionPerformed

    private void jmi_infodietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_infodietaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        DietaVista dieta = new DietaVista();
        dieta.setVisible(true);
        escritorio.add(dieta);
    }//GEN-LAST:event_jmi_infodietaActionPerformed

    private void jm_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_pacienteActionPerformed

    private void jmi_menusugeridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_menusugeridoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        MenuVista menuSugerido = new MenuVista();
        menuSugerido.setVisible(true);
        escritorio.add(menuSugerido);
    }//GEN-LAST:event_jmi_menusugeridoActionPerformed

    private void jmi_listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_listaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ListadoPacientes pacientes = new ListadoPacientes();
        pacientes.setVisible(true);
        escritorio.add(pacientes);
    }//GEN-LAST:event_jmi_listaActionPerformed

    private void jmi_verdietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_verdietaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VerDieta dietas = new VerDieta();
        dietas.setVisible(true);
        escritorio.add(dietas);
    }//GEN-LAST:event_jmi_verdietaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ComidaVista comida = new ComidaVista();
        comida.setVisible(true);
        escritorio.add(comida);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jm_consulta;
    private javax.swing.JMenu jm_dieta;
    private javax.swing.JMenu jm_paciente;
    private javax.swing.JMenuItem jmi_comidas;
    private javax.swing.JMenuItem jmi_infodieta;
    private javax.swing.JMenuItem jmi_infopaciente;
    private javax.swing.JMenuItem jmi_lista;
    private javax.swing.JMenuItem jmi_menusugerido;
    private javax.swing.JMenuItem jmi_verdieta;
    // End of variables declaration//GEN-END:variables

}
