package nutricion.vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import nutricion.modelo.MenuDiario;
import nutricion.modelo.RenglonComida;
import nutricion.persistencia.MenuDiarioData;
import nutricion.persistencia.RenglonComidaData;

/**
 *
 * @author ACER
 */
public class VerDieta extends javax.swing.JInternalFrame {

    private MenuDiarioData mddata;
    private MenuDiario md;
    private RenglonComidaData rcdata;
    private RenglonComida rc;

    private ArrayList<RenglonComida> renglonesMenu;

    private DefaultTableModel modelo;

    /**
     * Creates new form VerDieta
     */
    public VerDieta() {
        initComponents();
        this.setSize(600, 500);
        mddata = new MenuDiarioData();
        rcdata = new RenglonComidaData();
        modelo = new DefaultTableModel();
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_cod = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_dieta = new javax.swing.JTable();
        jb_verdieta = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Dieta");

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingrese el código de dieta:");

        jtf_cod.setBackground(new java.awt.Color(255, 102, 102));
        jtf_cod.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jtf_cod.setForeground(new java.awt.Color(0, 0, 0));

        jt_dieta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt_dieta);

        jb_verdieta.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jb_verdieta.setForeground(new java.awt.Color(255, 102, 102));
        jb_verdieta.setText("Ver dieta");
        jb_verdieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_verdietaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 70, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtf_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jb_verdieta)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addComponent(jb_verdieta)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_verdietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_verdietaActionPerformed
        borrarFilaTabla();
        Integer cod = Integer.parseInt(jtf_cod.getText());
        cargarDieta(cod);
        limpiar();
    }//GEN-LAST:event_jb_verdietaActionPerformed

    private void armarCabeceraTabla() {
        modelo.addColumn("Dia");
        modelo.addColumn("Alimento");
        modelo.addColumn("Cantidad (gr)");
        modelo.addColumn("Subtotal calorias");
        jt_dieta.setModel(modelo);
    }

    private void borrarFilaTabla() {
        int indice = modelo.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    private void cargarDieta(int codDieta) {
        ArrayList<MenuDiario> menus = mddata.obtenerMenusPorDieta(codDieta);

        for (MenuDiario menu : menus) {
            int diaNro = menu.getDiaNro();
            String nombreDia = obtenerNombreDelDia(diaNro);

            ArrayList<RenglonComida> renglones = rcdata.listarRenglonesPorMenu(menu.getCodMenu());

            for (RenglonComida r : renglones) {
                String alimento = r.getAlimento().getNombre();
                double cantidad = r.getCantidadGrs();
                int calorias = r.getSubtotalCalorias();

                modelo.addRow(new Object[]{"Día " + diaNro + " - " + nombreDia, alimento, cantidad, calorias});
            }
        }
    }

    private void limpiar() {
        jtf_cod.setText("");
    }

    private String obtenerNombreDelDia(int diaNro) {
        switch (diaNro) {
            case 1:
                return "Lunes";
            case 2:
                return "Martes";
            case 3:
                return "Miércoles";
            case 4:
                return "Jueves";
            case 5:
                return "Viernes";
            case 6:
                return "Sábado";
            case 7:
                return "Domingo";
            default:
                return "Día " + diaNro;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_verdieta;
    private javax.swing.JTable jt_dieta;
    private javax.swing.JTextField jtf_cod;
    // End of variables declaration//GEN-END:variables
}
